import { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

// 支持的语言列表（只保留简体中文、繁体中文和英语）
export const SUPPORTED_LANGUAGES = {
  'system': { code: 'system', name: '跟随系统', nativeName: '跟随系统' },
  'zh-CN': { code: 'zh-CN', name: '简体中文', nativeName: '简体中文' },
  'zh-TW': { code: 'zh-TW', name: '繁體中文', nativeName: '繁體中文' },
  'en': { code: 'en', name: 'English', nativeName: 'English' }
};

// 语言包
const translations = {
  'zh-CN': {
    // 设置页面
    'settings': '设置',
    'account-security': '账号与安全',
    'payment-settings': '支付设置',
    'mode-switch': '模式切换',
    'notification-settings': '新消息通知',
    'language-settings': '语言设置',
    'feedback': '反馈与投诉',
    'about': '关于',
    'version': '版本号',
    'switch-account': '登录其他账号',
    'logout': '退出登录',
    // 语言设置页面
    'language-title': '语言设置',
    'save': '保存',
    'follow-system': '跟随系统',
    // 登录页面
    'login-problem': '登录遇到问题',
    'app-name': '好医生在线',
    'phone-placeholder': '请输入手机号',
    'password-placeholder': '请输入密码',
    'forgot-password': '忘记密码?',
    'login': '登录',
    'logging': '登录中...',
    'login-failed': '登录失败，请检查手机号和密码',
    'enter-phone-password': '请输入手机号和密码',
    'agree-terms': '请先阅读并同意服务协议和隐私政策',
    'read-agreed': '已阅读并同意好医生在线',
    'service-agreement': '服务协议',
    'and': '和',
    'privacy-policy': '隐私政策',
    // 底部导航
    'home': '首页',
    'science': '科普',
    'ai-diagnosis': 'AI预诊',
    'community': '患友',
    'my': '我的',
    // 首页
    'search-hospital-drug': '搜索医院或药品',
    'search-doctor-by-disease-hospital-name': '根据疾病、医院、姓名找医生',
    'search': '搜索',
    'quick-buy': '快速购药',
    'same-day-delivery': '同城极速送达',
    'consultation': '咨询问诊',
    'doctor-online': '医生在线解答',
    'expert-online': '专家在线',
    'health-knowledge': '健康知识',
    'prescription': '开药问诊',
    'internal-medicine': '内科就诊',
    'more-categories': '更多分类',
    'loading-home': '首页数据加载中...',
    'recommended-doctors': '推荐医生',
    // 健康知识
    'hot-recommend': '热门推荐',
    'health-classroom': '养生课堂',
    'special-topic': '精彩专题',
    'expert-lecture': '专家讲堂',
    'health': '健康',
    'get-articles-failed': '获取文章失败',
    // 患友会
    'doctors-community': '医生的患友',
    'loading': '加载中...',
    'no-doctors': '暂无医生数据',
    // 个人中心
    'profile': '个人中心',
    'my-orders': '我的订单',
    'health-records': '健康记录',
    'family-members': '家庭成员',
    'my-favorites': '我的收藏',
    // 医生列表
    'search-department-doctor': '搜索科室或医生',
    'consult': '咨询',
    'people-consulted': '人已咨询',
    // 通用
    'back': '返回',
    'confirm': '确认',
    'cancel': '取消',
    'submit': '提交',
    'submitting': '提交中...',
    'success': '成功',
    'failed': '失败',
    'loading-text': '加载中...',
    'no-data': '暂无数据',
    'error': '错误',
    'view-all': '查看全部',
    'no-recommended-doctors': '暂无推荐医生',
    'medical-services': '医疗服务',
    'quick-call': '快捷电话',
    'private-doctor-callback': '私人医生回电',
    'text-emergency': '图文急诊',
    'expert-quick-reply': '专家快速回复',
    'video-diagnosis': '视频诊断',
    'professional-diagnosis': '专业医生诊断',
    'medicine-delivery': '送药上门',
    'fast-delivery': '要求快速到达',
    'load-doctors-failed': '加载医生列表失败',
    'no-doctors-data': '暂无医生数据，请更换筛选条件',
    'not-logged-in': '未登录',
    'fill-bio': '填写简介会收获更多粉丝哦~',
    'my-orders': '我的订单',
    'health-records': '健康记录',
    'family-members': '家庭成员',
    'my-favorites': '我的收藏',
    'todo': '待办事项',
    'my-consultation': '我的问诊',
    'consultant-service': '顾问服务',
    'merchant-service': '商家服务',
    'pending-payment': '待支付',
    'in-progress': '进行中',
    'completed': '已完成',
    'cancelled': '已取消',
    'my-services': '我的服务',
    'my-prescription': '我的处方',
    'my-reviews': '我的评价',
    'my-doctors': '我的医生',
    'my-profile': '我的资料',
    'my-medical-records': '我的病历',
    'load-more': '加载更多中...',
    'no-more': '没有更多了',
    'doctor-community': '医生的患友',
    // 健康知识页面
    'search-article-keyword': '搜索文章或关键字',
    'articles-loading': '文章加载中...',
    'no-related-articles': '暂无相关文章',
    'people-read': '人阅读',
    'platform-selected': '平台精选',
    // 医生列表页面
    'hot-departments': '热门科室',
    'cannot-load-departments': '无法加载科室信息',
    'cannot-load-doctors': '无法加载医生信息',
    'all-departments': '全部科室',
    // 发现页面
    'health-science': '健康科普',
    'featured': '精选',
    'favorites': '收藏',
    'subscriptions': '订阅',
    'please-login-favorites': '请先登录后查看收藏内容',
    'please-login-subscriptions': '请先登录后查看订阅内容',
    'load-articles-failed': '加载文章失败',
    'no-subscription-content': '暂无订阅内容',
    'no-content': '暂无内容',
    'from-doctor': '来自',
    'doctor-science': '医生的科普号',
    'read': '阅读',
    'favorite': '收藏',
    'go-subscribe': '去订阅',
    // 设置页面
    'standard-mode': '标准模式',
    'elder-mode': '长辈模式',
    // 账号安全
    'modify-phone': '修改绑定手机',
    'modify-password': '修改密码',
    'cancel-account': '注销账号',
    // 验证手机
    'enter-verification-code': '请输入验证码',
    'send-code': '发送验证码',
    'next-step': '下一步',
    // 修改密码
    'enter-sms-code': '请输入短信验证码',
    'reset-password': '重置密码',
    'current-account': '当前账号',
    'bound-phone': '已绑定手机',
    // 注销账号
    'apply-cancel': '申请注销',
    'important-reminder': '《重要提醒》',
    'cancel-reason': '注销原因',
    'confirm-cancel': '确认注销',
    'cancel-notice': '注销账号须知',
    // 反馈
    'feedback-title': '标题',
    'feedback-content': '反馈内容',
    'title-placeholder': '请输入反馈标题 (100字以内)',
    'content-placeholder': '请详细描述您遇到的问题或建议 (2000字以内)',
    'feedback-submit-success': '反馈提交成功！感谢您的宝贵意见。',
    'feedback-submit-failed': '提交反馈失败，请稍后再试。',
    'title-required': '标题不能为空',
    'content-required': '反馈内容不能为空',
    'title-too-long': '标题不能超过100个字符',
    'content-too-long': '反馈内容不能超过2000个字符',
    // 通知设置
    'notification-management': '通知管理',
    'receive-system-notification': '接受系统通知',
    'doctor-reply-message': '医生回复消息',
    'order-message': '订单消息',
    'platform-message': '平台消息',
    'enabled': '已开启',
    'disabled-go-settings': '已关闭, 去设置',
    'all-notifications': '所有"好大夫在线"通知',
    'not-allowed-notification': '您尚未允许此应用显示通知',
    'categories': '类别',
    'no-notifications-published': '此应用未发布任何通知',
    'allow-lock-screen-notification': '允许锁屏通知',
    // 系统信息
    'system-introduction': '系统介绍',
    'core-features': '核心功能',
    'contact-us': '联系我们',
    'online-consultation': '在线问诊',
    'health-science-knowledge': '健康科普',
    'patient-community': '患友',
    'health-records': '健康记录',
    'customer-service': '客服热线',
    'service-hours': '服务时间',
    'official-email': '官方邮箱',
    'copyright': '版权所有',
    // 患友会详情
    'group-rules': '会规',
    'reply-first': '回复优先',
    'publish-first': '发布优先',
    'create-post': '发帖',
    'post-title': '标题',
    'post-content': '内容',
    'select-image-video': '选择图片/视频',
    'voice-to-text': '语音转文字',
    'publish': '发布',
    'publishing': '发布中...',
    'post-title-placeholder': '请输入标题',
    'post-content-placeholder': '请输入内容',
    'recording': '录音中...',
    'stop-recording': '停止录音',
    'start-recording': '开始录音',
    'no-recording-support': '您的浏览器不支持语音识别功能',
    'recording-error': '录音出错，请重试',
    'recording-permission-denied': '需要麦克风权限才能使用语音转文字功能',
    // 订阅管理
    'subscription-management': '订阅管理',
    'doctors-under-department': '科室下的医生',
    'subscribe': '订阅',
    'subscribed': '已订阅',
    'unsubscribe': '取消订阅',
    'no-doctors-in-department': '该科室暂无医生',
    // 其他
    'fans': '粉丝',
    'reads': '阅读',
    'online': '在线',
    'more': '更多',
    'department': '科室',
    'hospital': '医院',
    'confirm-logout': '确定要退出登录吗？',
    'confirm-switch-account': '确定要切换账号吗？',
    'submit-feedback': '提交反馈',
    'system-notification': '系统通知',
    'app-message-notification': 'APP消息通知',
    'warm-tips': '温馨提示',
    'tip-describe-detail': '请详细描述您遇到的问题或建议',
    'tip-process-time': '我们会在1-3个工作日内处理您的反馈',
    'tip-customer-service': '紧急问题请联系客服热线',
    'system-info': '系统信息',
    'medical-consultation-system': '医疗问诊系统',
    'system-intro-text': '本医疗问诊系统致力于为用户提供便捷、高效的在线医疗咨询服务。我们汇聚了众多专业医生，涵盖多个科室，旨在帮助用户随时随地获取专业的健康建议和诊疗指导。',
    'online-consultation-desc': '在线咨询专业医生，获取健康建议',
    'health-science-desc': '浏览健康科普文章，学习健康知识',
    'patient-community-desc': '加入患友，与其他患者交流经验',
    'health-records-desc': '记录和管理个人健康档案',
    'service-hours-value': '周一至周日 9:00 - 18:00',
    'all-rights-reserved': 'All rights reserved.',
    'search-department-keyword': '搜索科室或关键字',
    'please-select-department': '请选择科室',
    'specialty-info-missing': '擅长信息暂缺',
    'no-related-doctors': '暂无相关医生',
    'doctor-wang': '王医生',
    'doctor': '医生',
    'me': '我',
    'image': '图片',
    'input-message': '输入消息',
    'send': '发送',
    'cannot-load-doctor-detail': '无法加载医生详情',
    'doctor-info-loading': '医生信息加载中...',
    'expert-consultation': '专家问诊',
    'normal-consultation': '普通问诊',
    'confirm-logout': '确定要退出登录吗？',
    'confirm-switch-account': '确定要切换账号吗？',
    'submit-feedback': '提交反馈',
    'warm-tips': '温馨提示',
    'tip-describe-detail': '请详细描述您遇到的问题或建议',
    'tip-process-time': '我们会在1-3个工作日内处理您的反馈',
    'tip-customer-service': '如需紧急处理，请联系客服热线',
    'system-info': '系统信息',
    'medical-consultation-system': '医疗问诊系统',
    'system-intro-text': '医疗问诊系统是一款专业的在线医疗咨询平台，致力于为用户提供便捷、高效的医疗服务。系统集成了医生在线咨询、健康知识科普、患友社区等多项功能，让用户足不出户即可享受专业医疗咨询服务。',
    'online-consultation-desc': '与专业医生在线交流，获得专业医疗建议',
    'health-science-desc': '浏览丰富的健康知识文章，提升健康意识',
    'patient-community-desc': '加入医生患友，与病友交流分享经验',
    'health-records-desc': '记录和管理个人健康档案，方便随时查看',
    'service-hours-value': '周一至周日 9:00-21:00',
    'all-rights-reserved': 'All Rights Reserved',
    'system-notification': '系统通知',
    'app-message-notification': 'APP消息通知',
    'search-department-keyword': '搜索科室关键词',
    'please-select-department': '请选择科室',
    'specialty-info-missing': '擅长信息暂缺',
    'no-related-doctors': '暂无相关医生',
    'doctor-wang': '王医生',
    'doctor': '医生',
    'me': '我',
    'image': '图片',
    'input-message': '输入消息...',
    'send': '发送',
    'cannot-load-doctor-detail': '无法获取医生详情',
    'doctor-info-loading': '医生信息加载中...',
    'online-consultation': '线上问诊',
    'general-waiting-time': '一般等待时间',
    'hours': '小时',
    'consultation-notice': '以下服务均可上传文字、图片、视频和影像检查等资料',
    'phone-consultation': '电话问诊',
    'text-consultation': '图文问诊',
    'video-consultation': '视频问诊',
    'service-description': '服务说明',
    'phone-consult-feature1': '需要对病情非常清楚的人和医生通话,并且提交齐全的病情资料',
    'phone-consult-feature2': '通话前建议准备好针对病情的具体问题,跟医生讨论或请医生讲解',
    'text-consult-feature1': '适合需要详细文字描述病情并希望得到医生详细文字回复的用户',
    'text-consult-feature2': '可以上传图片、视频等资料,医生会在2天内回复',
    'video-consult-feature1': '适合需要面对面交流,希望看到医生表情和手势的用户',
    'video-consult-feature2': '可以实时与医生视频通话,医生会在预约时间内接听',
    'yuan': '元',
    'per': '/',
    'minutes': '分钟',
    'days': '天',
    'please-enter-title': '请输入标题',
    'please-enter-content': '请输入内容',
    'content-too-long-1000': '内容不能超过1000字',
    'upload': '上传',
    'video': '视频',
    'publish-failed': '发布失败',
    'preview': '预览',
    'please-speak': '请说话',
    'listening': '正在聆听...',
    'finished-speaking': '说完了',
    'complete': '完成',
    'characters': '字',
    'recording-click-stop': '正在录音，点击停止',
    'post-content-placeholder-create': '请写下您想让患者了解的内容...',
    'load-data-failed': '加载数据失败',
    'today': '今天',
    'days-ago': '天前',
    'weeks-ago': '周前',
    'months-ago': '个月前',
    'years-ago': '年前',
    'group-not-exist': '患友不存在',
    'people-published': '人发布',
    'people-viewed': '人看过',
    'post-order': '看帖顺序',
    'no-posts': '暂无帖子',
    'avatar': '头像',
    'replied-at': '回复于',
    'share': '分享',
    'comment': '评论',
    'like': '赞',
    'post-detail': '帖子详情',
    'all-replies': '全部回复',
    'no-replies': '暂无回复',
    'click-to-comment': '点击这里说点什么吧',
    'say-something': '我来说几句...',
    'views': '浏览量',
    'post-not-exist': '帖子不存在',
    'comment-failed': '评论失败',
    'personal-introduction': '个人简介',
    'no-personal-introduction': '暂无个人简介',
    'please-select-consultation-type': '请先选择问诊方式',
    'apply-now': '立即申请',
    'subscription-doctor': '订阅医生',
    'all': '全部',
    'unsubscribe-failed': '取消订阅失败',
    'subscribe-failed': '订阅失败',
    'verify-phone': '验证手机号',
    'verify-current-phone': '请验证当前绑定手机号',
    'enter-bound-phone': '请输入已绑定的手机号',
    'enter-6-digit-code': '请输入6位验证码',
    'get-code': '获取验证码',
    'seconds': '秒',
    'phone-format-incorrect': '手机号格式不正确',
    'verify-current-bound-phone': '请验证当前绑定手机',
    'bound-phone-label': '绑定手机',
    'reset-password': '重置密码',
    'current-account-label': '当前账号',
    'enter-new-password-hint': '请输入新密码 (6-20位字母或数字)',
    'enter-new-password': '输入新密码',
    'enter-new-password-again': '再次输入新密码',
    'password-length-error': '密码长度为6-20位',
    'password-format-error': '密码只能包含字母或数字',
    'password-mismatch': '两次输入的密码不一致',
    'password-reset-success': '密码重置成功，请使用新密码登录',
    'password-reset-failed': '密码重置失败，请重试',
    'setting': '设置中...',
    'set-new-password': '设置新密码',
    'cancel-account': '注销账号',
    'apply-cancel-account': '申请注销账号',
    'cancel-warning1': '注销后,您与医生的交流记录将丢失!',
    'cancel-warning2': '注销后,您上传的病历资料将丢失',
    'cancel-warning3': '注销后,账户余额等资产权益将丢失!',
    'return': '返回',
    'click-apply-means': '点击申请注销按钮,即表示您',
    'read-agree': '已阅读并同意',
    'cancel-reason': '注销原因',
    'tell-us-reason': '请告诉我们注销的原因来帮助完善我们的服务',
    'security-privacy': '安全/隐私顾虑',
    'new-phone': '使用新的手机号',
    'bad-experience': '体验不好,没能解决我的问题',
    'multiple-accounts': '我有多个账号',
    'not-needed': '不再需要',
    'other-reason': '其他原因',
    'more-privacy': '更多隐私保护内容',
    'confirm-cancel': '确认注销',
    'cancelling-account': '您正在注销的账号是',
    'confirm-cancel-account': '确认注销账号吗？此操作不可恢复！',
    'account-cancelled': '账号已注销',
    'cancel-notice': '注销账号须知',
    'important': '【重要】',
    'cancel-irreversible': '注销账号是不可恢复的操作。注销前请确认您的资料已妥善处理。',
    'cancel-notice1': '您将无法再登录和使用本账号,包括但不限于PC端、微信小程序、移动客户端等,也无法通过忘记密码操作来找回。',
    'cancel-notice2': '您未完成的订单及服务将无法继续,也无法退款。',
    'cancel-notice3': '账号中的余额、好豆、公益补贴券,进行中的退款或提现将视为您自行放弃。',
    'cancel-notice4': '除法律法规要求必须保存的信息以外,您的用户信息我们将予以删除。您账号下所有行为信息记录,您将无法找回。',
    'cancel-notice5': '注销账号并不代表本账号注销前的行为和相关责任得到豁免或减轻。',
    'special-notice': '【特别提示】',
    'special-notice-text': '当您按照注销页面提示填写信息、阅读并同意本《注销须知》及相关条款与条件且完成全部注销程序后,即表示您已充分阅读、理解并接受本《注销须知》的全部内容。阅读本《注销须知》的过程中,如果您不同意相关任何条款和条件约束,请您立即停止账号注销。',
    'load-rules-failed': '加载会规失败',
    'rules-not-exist': '会规不存在',
    'group-rules-title': '患友守则',
    'ten-thousand': '万'
  },
  'en': {
    'settings': 'Settings',
    'account-security': 'Account & Security',
    'payment-settings': 'Payment Settings',
    'mode-switch': 'Mode Switch',
    'notification-settings': 'New Message Notification',
    'language-settings': 'Language Settings',
    'feedback': 'Feedback & Complaints',
    'about': 'About',
    'version': 'Version',
    'switch-account': 'Login to other accounts',
    'logout': 'Logout',
    'language-title': 'Language Settings',
    'save': 'Save',
    'follow-system': 'Follow System',
    'login-problem': 'Login Problem',
    'app-name': 'Good Doctor Online',
    'phone-placeholder': 'Enter phone number',
    'password-placeholder': 'Enter password',
    'forgot-password': 'Forgot Password?',
    'login': 'Login',
    'logging': 'Logging in...',
    'login-failed': 'Login failed, please check phone number and password',
    'enter-phone-password': 'Please enter phone number and password',
    'agree-terms': 'Please read and agree to the service agreement and privacy policy',
    'read-agreed': 'I have read and agree to Good Doctor Online',
    'service-agreement': 'Service Agreement',
    'and': 'and',
    'privacy-policy': 'Privacy Policy',
    'home': 'Home',
    'science': 'Science',
    'ai-diagnosis': 'AI Diagnosis',
    'community': 'Community',
    'my': 'My',
    'search-hospital-drug': 'Search hospital or drug',
    'search-doctor-by-disease-hospital-name': 'Search for doctors by disease, hospital, or name',
    'search': 'Search',
    'quick-buy': 'Quick Buy',
    'same-day-delivery': 'Same-day delivery',
    'consultation': 'Consultation',
    'doctor-online': 'Doctor online answers',
    'expert-online': 'Expert Online',
    'expert-consultation': 'Expert Consultation',
    'normal-consultation': 'Normal Consultation',
    'health-knowledge': 'Health Knowledge',
    'prescription': 'Prescription',
    'internal-medicine': 'Internal Medicine',
    'more-categories': 'More Categories',
    'loading-home': 'Loading home data...',
    'recommended-doctors': 'Recommended Doctors',
    'hot-recommend': 'Hot Recommend',
    'health-classroom': 'Health Classroom',
    'special-topic': 'Special Topic',
    'expert-lecture': 'Expert Lecture',
    'health': 'Health',
    'get-articles-failed': 'Failed to get articles',
    'doctors-community': 'Doctors Community',
    'loading': 'Loading...',
    'no-doctors': 'No doctor data',
    'profile': 'Profile',
    'my-orders': 'My Orders',
    'health-records': 'Health Records',
    'family-members': 'Family Members',
    'my-favorites': 'My Favorites',
    'search-department-doctor': 'Search department or doctor',
    'consult': 'Consult',
    'people-consulted': 'people consulted',
    'back': 'Back',
    'confirm': 'Confirm',
    'cancel': 'Cancel',
    'submit': 'Submit',
    'submitting': 'Submitting...',
    'success': 'Success',
    'failed': 'Failed',
    'loading-text': 'Loading...',
    'no-data': 'No Data',
    'error': 'Error',
    'view-all': 'View All',
    'no-recommended-doctors': 'No recommended doctors',
    'medical-services': 'Medical Services',
    'quick-call': 'Quick Call',
    'private-doctor-callback': 'Private doctor callback',
    'text-emergency': 'Text Emergency',
    'expert-quick-reply': 'Expert quick reply',
    'video-diagnosis': 'Video Diagnosis',
    'professional-diagnosis': 'Professional doctor diagnosis',
    'medicine-delivery': 'Medicine Delivery',
    'fast-delivery': 'Fast delivery required',
    'load-doctors-failed': 'Failed to load doctor list',
    'no-doctors-data': 'No doctor data, please change filter conditions',
    'not-logged-in': 'Not Logged In',
    'fill-bio': 'Fill in your bio to get more followers~',
    'my-orders': 'My Orders',
    'health-records': 'Health Records',
    'family-members': 'Family Members',
    'my-favorites': 'My Favorites',
    'todo': 'Todo',
    'my-consultation': 'My Consultation',
    'consultant-service': 'Consultant Service',
    'merchant-service': 'Merchant Service',
    'pending-payment': 'Pending Payment',
    'in-progress': 'In Progress',
    'completed': 'Completed',
    'cancelled': 'Cancelled',
    'my-services': 'My Services',
    'my-prescription': 'My Prescription',
    'my-reviews': 'My Reviews',
    'my-doctors': 'My Doctors',
    'my-profile': 'My Profile',
    'my-medical-records': 'My Medical Records',
    'load-more': 'Loading more...',
    'no-more': 'No more',
    'doctor-community': 'Doctor Community',
    'search-article-keyword': 'Search articles or keywords',
    'articles-loading': 'Loading articles...',
    'no-related-articles': 'No related articles',
    'people-read': ' people read',
    'platform-selected': 'Platform Selected',
    'hot-departments': 'Hot Departments',
    'cannot-load-departments': 'Cannot load department information',
    'cannot-load-doctors': 'Cannot load doctor information',
    'all-departments': 'All Departments',
    'health-science': 'Health Science',
    'featured': 'Featured',
    'favorites': 'Favorites',
    'subscriptions': 'Subscriptions',
    'please-login-favorites': 'Please login to view favorites',
    'please-login-subscriptions': 'Please login to view subscriptions',
    'load-articles-failed': 'Failed to load articles',
    'no-subscription-content': 'No subscription content',
    'no-content': 'No content',
    'from-doctor': 'From ',
    'doctor-science': ' doctor\'s science account',
    'read': 'Read',
    'favorite': 'Favorite',
    'go-subscribe': 'Go Subscribe',
    'standard-mode': 'Standard Mode',
    'elder-mode': 'Elder Mode',
    'modify-phone': 'Modify Bound Phone',
    'modify-password': 'Modify Password',
    'cancel-account': 'Cancel Account',
    'enter-verification-code': 'Enter verification code',
    'send-code': 'Send Code',
    'next-step': 'Next Step',
    'enter-sms-code': 'Enter SMS verification code',
    'reset-password': 'Reset Password',
    'current-account': 'Current Account',
    'bound-phone': 'Bound Phone',
    'apply-cancel': 'Apply Cancel',
    'important-reminder': 'Important Reminder',
    'cancel-reason': 'Cancel Reason',
    'confirm-cancel': 'Confirm Cancel',
    'cancel-notice': 'Cancel Account Notice',
    'feedback-title': 'Title',
    'feedback-content': 'Feedback Content',
    'title-placeholder': 'Enter feedback title (max 100 characters)',
    'content-placeholder': 'Describe your issue or suggestion in detail (max 2000 characters)',
    'feedback-submit-success': 'Feedback submitted successfully! Thank you for your valuable feedback.',
    'feedback-submit-failed': 'Failed to submit feedback, please try again later.',
    'title-required': 'Title cannot be empty',
    'content-required': 'Feedback content cannot be empty',
    'title-too-long': 'Title cannot exceed 100 characters',
    'content-too-long': 'Feedback content cannot exceed 2000 characters',
    'notification-management': 'Notification Management',
    'receive-system-notification': 'Receive System Notifications',
    'doctor-reply-message': 'Doctor Reply Messages',
    'order-message': 'Order Messages',
    'platform-message': 'Platform Messages',
    'enabled': 'Enabled',
    'disabled-go-settings': 'Disabled, Go Settings',
    'all-notifications': 'All "Good Doctor Online" Notifications',
    'not-allowed-notification': 'You have not yet allowed this app to display notifications',
    'categories': 'Categories',
    'no-notifications-published': 'This app has not published any notifications',
    'allow-lock-screen-notification': 'Allow Lock Screen Notifications',
    'system-introduction': 'System Introduction',
    'core-features': 'Core Features',
    'contact-us': 'Contact Us',
    'online-consultation': 'Online Consultation',
    'health-science-knowledge': 'Health Science Knowledge',
    'patient-community': 'Patient Community',
    'customer-service': 'Customer Service Hotline',
    'service-hours': 'Service Hours',
    'official-email': 'Official Email',
    'copyright': 'Copyright',
    'group-rules': 'Group Rules',
    'reply-first': 'Reply First',
    'publish-first': 'Publish First',
    'create-post': 'Create Post',
    'post-title': 'Title',
    'post-content': 'Content',
    'select-image-video': 'Select Image/Video',
    'voice-to-text': 'Voice to Text',
    'publish': 'Publish',
    'publishing': 'Publishing...',
    'post-title-placeholder': 'Enter title',
    'post-content-placeholder': 'Enter content',
    'recording': 'Recording...',
    'stop-recording': 'Stop Recording',
    'start-recording': 'Start Recording',
    'no-recording-support': 'Your browser does not support voice recognition',
    'recording-error': 'Recording error, please try again',
    'recording-permission-denied': 'Microphone permission required for voice-to-text',
    'subscription-management': 'Subscription Management',
    'doctors-under-department': 'Doctors Under Department',
    'subscribe': 'Subscribe',
    'subscribed': 'Subscribed',
    'unsubscribe': 'Unsubscribe',
    'no-doctors-in-department': 'No doctors in this department',
    'fans': ' fans',
    'reads': ' reads',
    'online': 'Online',
    'more': 'More',
    'department': 'Department',
    'hospital': 'Hospital',
    'confirm-logout': 'Are you sure you want to logout?',
    'confirm-switch-account': 'Are you sure you want to switch account?',
    'submit-feedback': 'Submit Feedback',
    'warm-tips': 'Warm Tips',
    'tip-describe-detail': 'Please describe your issue or suggestion in detail',
    'tip-process-time': 'We will process your feedback within 1-3 business days',
    'tip-customer-service': 'For urgent matters, please contact customer service hotline',
    'system-info': 'System Info',
    'medical-consultation-system': 'Medical Consultation System',
    'system-intro-text': 'Medical Consultation System is a professional online medical consultation platform dedicated to providing convenient and efficient medical services to users. The system integrates multiple functions such as online doctor consultation, health knowledge popularization, and patient community, allowing users to enjoy professional medical consultation services without leaving home.',
    'online-consultation-desc': 'Communicate with professional doctors online and get professional medical advice',
    'health-science-desc': 'Browse rich health knowledge articles to improve health awareness',
    'patient-community-desc': 'Join doctor patient communities to exchange and share experiences with patients',
    'health-records-desc': 'Record and manage personal health records for easy access anytime',
    'service-hours-value': 'Monday to Sunday 9:00-21:00',
    'all-rights-reserved': 'All Rights Reserved',
    'system-notification': 'System Notification',
    'app-message-notification': 'APP Message Notification',
    'replied-at': 'Replied at',
    'share': 'Share',
    'comment': 'Comment',
    'like': 'Like',
    'post-detail': 'Post Detail',
    'all-replies': 'All Replies',
    'no-replies': 'No replies yet',
    'click-to-comment': 'Click here to say something',
    'say-something': 'Say a few words...',
    'views': 'Views',
    'post-not-exist': 'Post does not exist',
    'comment-failed': 'Comment failed'
  },
  'zh-TW': {
    'settings': '設置',
    'account-security': '賬號與安全',
    'payment-settings': '支付設置',
    'mode-switch': '模式切換',
    'notification-settings': '新消息通知',
    'language-settings': '語言設置',
    'feedback': '反饋與投訴',
    'about': '關於',
    'version': '版本号',
    'switch-account': '登錄其他賬號',
    'logout': '退出登录',
    'language-title': '語言設置',
    'save': '保存',
    'follow-system': '跟隨系統',
    'login-problem': '登錄遇到問題',
    'app-name': '好醫生在線',
    'phone-placeholder': '請輸入手機號',
    'password-placeholder': '請輸入密碼',
    'forgot-password': '忘記密碼?',
    'login': '登錄',
    'logging': '登錄中...',
    'login-failed': '登錄失敗，請檢查手機號和密碼',
    'enter-phone-password': '請輸入手機號和密碼',
    'agree-terms': '請先閱讀並同意服務協議和隱私政策',
    'read-agreed': '已閱讀並同意好醫生在線',
    'service-agreement': '服務協議',
    'and': '和',
    'privacy-policy': '隱私政策',
    'home': '首頁',
    'science': '科普',
    'ai-diagnosis': 'AI預診',
    'community': '患友',
    'my': '我的',
    'search-hospital-drug': '搜索醫院或藥品',
    'search-doctor-by-disease-hospital-name': '根據疾病、醫院、姓名找醫生',
    'search': '搜索',
    'quick-buy': '快速購藥',
    'same-day-delivery': '同城極速送達',
    'consultation': '諮詢問診',
    'doctor-online': '醫生在線解答',
    'expert-online': '專家在線',
    'expert-consultation': '專家問診',
    'normal-consultation': '普通問診',
    'health-knowledge': '健康知識',
    'prescription': '開藥問診',
    'internal-medicine': '內科就診',
    'more-categories': '更多分類',
    'loading-home': '首頁數據加載中...',
    'recommended-doctors': '推薦醫生',
    'hot-recommend': '熱門推薦',
    'health-classroom': '養生課堂',
    'special-topic': '精彩專題',
    'expert-lecture': '專家講堂',
    'health': '健康',
    'get-articles-failed': '獲取文章失敗',
    'doctors-community': '醫生的患友會',
    'loading': '加載中...',
    'no-doctors': '暫無醫生數據',
    'profile': '個人中心',
    'my-orders': '我的訂單',
    'health-records': '健康記錄',
    'family-members': '家庭成員',
    'my-favorites': '我的收藏',
    'search-department-doctor': '搜索科室或醫生',
    'consult': '諮詢',
    'people-consulted': '人已諮詢',
    'back': '返回',
    'confirm': '確認',
    'cancel': '取消',
    'submit': '提交',
    'submitting': '提交中...',
    'success': '成功',
    'failed': '失敗',
    'loading-text': '加載中...',
    'no-data': '暫無數據',
    'error': '錯誤',
    'view-all': '查看全部',
    'no-recommended-doctors': '暫無推薦醫生',
    'medical-services': '醫療服務',
    'quick-call': '快捷電話',
    'private-doctor-callback': '私人醫生回電',
    'text-emergency': '圖文急診',
    'expert-quick-reply': '專家快速回復',
    'video-diagnosis': '視頻診斷',
    'professional-diagnosis': '專業醫生診斷',
    'medicine-delivery': '送藥上門',
    'fast-delivery': '要求快速到达',
    'load-doctors-failed': '加載醫生列表失敗',
    'no-doctors-data': '暫無醫生數據，請更換篩選條件',
    'not-logged-in': '未登录',
    'fill-bio': '填寫簡介會收獲更多粉絲哦~',
    'my-orders': '我的訂單',
    'health-records': '健康記錄',
    'family-members': '家庭成員',
    'my-favorites': '我的收藏',
    'todo': '待辦事項',
    'my-consultation': '我的問診',
    'consultant-service': '顧問服務',
    'merchant-service': '商家服務',
    'pending-payment': '待支付',
    'in-progress': '進行中',
    'completed': '已完成',
    'cancelled': '已取消',
    'my-services': '我的服務',
    'my-prescription': '我的處方',
    'my-reviews': '我的評價',
    'my-doctors': '我的醫生',
    'my-profile': '我的資料',
    'my-medical-records': '我的病歷',
    'load-more': '加載更多中...',
    'no-more': '沒有更多了',
    'doctor-community': '醫生的患友會',
    'search-article-keyword': '搜索文章或關鍵字',
    'articles-loading': '文章加載中...',
    'no-related-articles': '暫無相關文章',
    'people-read': '人閱讀',
    'platform-selected': '平台精選',
    'hot-departments': '熱門科室',
    'cannot-load-departments': '無法加載科室信息',
    'cannot-load-doctors': '無法加載醫生信息',
    'all-departments': '全部科室',
    'health-science': '健康科普',
    'featured': '精選',
    'favorites': '收藏',
    'subscriptions': '訂閱',
    'please-login-favorites': '請先登錄後查看收藏內容',
    'please-login-subscriptions': '請先登錄後查看訂閱內容',
    'load-articles-failed': '加載文章失敗',
    'no-subscription-content': '暫無訂閱內容',
    'no-content': '暫無內容',
    'from-doctor': '來自',
    'doctor-science': '醫生的科普號',
    'read': '閱讀',
    'favorite': '收藏',
    'go-subscribe': '去訂閱',
    'standard-mode': '標準模式',
    'elder-mode': '長輩模式',
    'modify-phone': '修改綁定手機',
    'modify-password': '修改密碼',
    'cancel-account': '註銷賬號',
    'enter-verification-code': '請輸入驗證碼',
    'send-code': '發送驗證碼',
    'next-step': '下一步',
    'enter-sms-code': '請輸入短信驗證碼',
    'reset-password': '重置密碼',
    'current-account': '當前賬號',
    'bound-phone': '已綁定手機',
    'apply-cancel': '申請註銷',
    'important-reminder': '《重要提醒》',
    'cancel-reason': '註銷原因',
    'confirm-cancel': '確認註銷',
    'cancel-notice': '註銷賬號須知',
    'feedback-title': '標題',
    'feedback-content': '反饋內容',
    'title-placeholder': '請輸入反饋標題 (100字以內)',
    'content-placeholder': '請詳細描述您遇到的問題或建議 (2000字以內)',
    'feedback-submit-success': '反饋提交成功！感謝您的寶貴意見。',
    'feedback-submit-failed': '提交反饋失敗，請稍後再試。',
    'title-required': '標題不能為空',
    'content-required': '反饋內容不能為空',
    'title-too-long': '標題不能超過100個字符',
    'content-too-long': '反饋內容不能超過2000個字符',
    'notification-management': '通知管理',
    'receive-system-notification': '接受系統通知',
    'doctor-reply-message': '醫生回復消息',
    'order-message': '訂單消息',
    'platform-message': '平台消息',
    'enabled': '已開啟',
    'disabled-go-settings': '已關閉, 去設置',
    'all-notifications': '所有"好大夫在线"通知',
    'not-allowed-notification': '您尚未允許此應用顯示通知',
    'categories': '類別',
    'no-notifications-published': '此應用未發布任何通知',
    'allow-lock-screen-notification': '允許鎖屏通知',
    'system-introduction': '系統介紹',
    'core-features': '核心功能',
    'contact-us': '聯繫我們',
    'online-consultation': '在線問診',
    'health-science-knowledge': '健康科普',
    'patient-community': '患友',
    'customer-service': '客服熱線',
    'service-hours': '服務時間',
    'official-email': '官方郵箱',
    'copyright': '版權所有',
    'group-rules': '會規',
    'replied-at': '回復於',
    'share': '分享',
    'comment': '評論',
    'like': '讚',
    'post-detail': '帖子詳情',
    'all-replies': '全部回復',
    'no-replies': '暫無回復',
    'click-to-comment': '點擊這裡說點什麼吧',
    'say-something': '我來說幾句...',
    'views': '瀏覽量',
    'post-not-exist': '帖子不存在',
    'comment-failed': '評論失敗',
    'reply-first': '回復優先',
    'publish-first': '發布優先',
    'create-post': '發帖',
    'post-title': '標題',
    'post-content': '內容',
    'select-image-video': '選擇圖片/視頻',
    'voice-to-text': '語音轉文字',
    'publish': '發布',
    'publishing': '發布中...',
    'post-title-placeholder': '請輸入標題',
    'post-content-placeholder': '請輸入內容',
    'recording': '錄音中...',
    'stop-recording': '停止錄音',
    'start-recording': '開始錄音',
    'no-recording-support': '您的瀏覽器不支持語音識別功能',
    'recording-error': '錄音出錯，請重試',
    'recording-permission-denied': '需要麥克風權限才能使用語音轉文字功能',
    'subscription-management': '訂閱管理',
    'doctors-under-department': '科室下的醫生',
    'subscribe': '訂閱',
    'subscribed': '已訂閱',
    'unsubscribe': '取消訂閱',
    'no-doctors-in-department': '該科室暫無醫生',
    'fans': '粉絲',
    'reads': '閱讀',
    'online': '在線',
    'more': '更多',
    'department': '科室',
    'hospital': '醫院',
    'confirm-logout': '確定要退出登錄嗎？',
    'confirm-switch-account': '確定要切換賬號嗎？',
    'submit-feedback': '提交反饋',
    'warm-tips': '溫馨提示',
    'tip-describe-detail': '請詳細描述您遇到的問題或建議',
    'tip-process-time': '我們會在1-3個工作日內處理您的反饋',
    'tip-customer-service': '如需緊急處理，請聯繫客服熱線',
    'system-info': '系統信息',
    'medical-consultation-system': '醫療問診系統',
    'system-intro-text': '醫療問診系統是一款專業的在線醫療諮詢平台，致力於為用戶提供便捷、高效的醫療服務。系統集成了醫生在線諮詢、健康知識科普、患友會社區等多項功能，讓用戶足不出戶即可享受專業醫療諮詢服務。',
    'online-consultation-desc': '與專業醫生在線交流，獲得專業醫療建議',
    'health-science-desc': '瀏覽豐富的健康知識文章，提升健康意識',
    'patient-community-desc': '加入醫生患友會，與病友交流分享經驗',
    'health-records-desc': '記錄和管理個人健康檔案，方便隨時查看',
    'service-hours-value': '週一至週日 9:00-21:00',
    'all-rights-reserved': 'All Rights Reserved',
    'system-notification': '系統通知',
    'app-message-notification': 'APP消息通知'
  }
};

// 获取系统语言
const getSystemLanguage = () => {
  const systemLang = navigator.language || navigator.userLanguage;
  // 映射到支持的语言代码
  if (systemLang.startsWith('zh')) {
    if (systemLang.includes('TW') || systemLang.includes('HK')) {
      return systemLang.includes('HK') ? 'zh-HK' : 'zh-TW';
    }
    return 'zh-CN';
  }
  // 检查是否支持系统语言
  const supportedCodes = Object.keys(SUPPORTED_LANGUAGES).filter(k => k !== 'system');
  if (supportedCodes.includes(systemLang)) {
    return systemLang;
  }
  return 'zh-CN'; // 默认简体中文
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem('app-language');
    return saved || 'system';
  });

  useEffect(() => {
    localStorage.setItem('app-language', language);
    
    // 设置HTML lang属性
    const actualLang = language === 'system' ? getSystemLanguage() : language;
    document.documentElement.lang = actualLang;
    
    // 触发页面刷新以更新所有翻译
    // 通过更新一个状态来强制重新渲染所有使用 useLanguage 的组件
    window.dispatchEvent(new Event('languagechange'));
  }, [language]);

  const t = (key) => {
    const actualLang = language === 'system' ? getSystemLanguage() : language;
    const langPack = translations[actualLang] || translations['zh-CN'];
    return langPack[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}
